### ISSUE TITLE
This is dangerously incorrect

### ISSUE THREAD

**Issue by StoneCypher** [delventhalz/browser-hash#1]
> The interface is named subtle because it warns developers that many of the crypto algorithms have sophisticated usage requirements that must be strictly followed to get the expected algorithmic security guarantees. The subtle object is the main entry point for interacting with underlying crypto primitives.

You are not following these usage requirements, and the security guarantees are lost.

You are burying, apparently intentionally, all warnings to developers that their use of your library is deeply insecure.

Please reconsider this library.  Its usage structure cannot be repaired; you are passing too much of the buck to the downstream user, and hiding from them the information they need to do something correct.

The first law of the internet: "if you are not a cryptography expert, do not attempt to get involved."

**Comment by StoneCypher** [comment]
This is particularly concerning coming from a cryptocurrency person.

Anyone with even a two week red team training program can walk right through this like it isn't even there.

This system is how bridges get owned, dude, is people like you saying "I'm going to make the hard parts easier" without recognizing the wild, wild damage they're doing

**Comment by delventhalz** [comment]
> Note that this library is not intended for cryptographic purposes. If you need cryptographically secure hashing, there are extra steps you may need to take which this library will not be suited for.

This is the second sentence from my README. The first sentence links to the MDN documentation for Web Crypto, where you will find a similar warning to the one you quoted.

I very explicitly did not build this library as a security tool. I am not intentionally burying any information, and I don't know what gives you that impression. If you have suggestions for how I can more clearly warn developers about the limitations of this library, I am all ears and would be very likely to implement them.

But while I appreciate the feedback, and would love to continue the discussion if you are interested, I reject the implication that there is no non-security use case for fast, easy, browser-side hashing. This library does not wrap Web Crypto's encryption or signing functionality. It is only for hashing and makes no security guarantees about those hashes. Being able to uniquely identify some data with a short deterministic string is occasionally handy. I for one appreciate not having to make a big ceremony out of it when that ceremony is unnecessary.

**Comment by delventhalz** [comment]
In the interest of being as clear as possible about the use case for this library, I have reworded the warning at the beginning of the README to be more dire and formatted it as a callback.

https://github.com/delventhalz/browser-hash/commit/44c33a41d750c320c59583afa4d04c63fae215ab

If you have any further suggestions other than deleting the library entirely, I am very interested to hear them.

**Comment by StoneCypher** [comment]
It's bad for even casual use.  This is literally the exact mistake that the
Chrome team made.



> If you have any further suggestions other than deleting the library
entirely

Well, you could take the time to learn the difficult things that this name
was chosen to warn people about, and do them correctly, but between you and
me, I think that's even less likely than causing indirect harm because you
want to be a library author and don't grok the downside

There aren't even any t tests here, buddy

This is one of the six warning topics for a reason :(

This took more than two decades to get into the browser for a reason :(

But I guess I feel like we're already pretty clear into "I'm gonna do what
I want" territory.  You have fun

**Comment by delventhalz** [comment]
Thanks for your thoughts. If you have anything more specific to add later, I'll be here. Closing this issue for now.
